<?xml version="1.0" encoding="utf-8"?><Database Name="pass123db" Class="PasswordManagerDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=pass123.database.windows.net;Initial Catalog=pass123db;User ID=cpsc362" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="pass123dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserInfo" Member="UserInfos">
    <Type Name="UserInfo">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MasterPassword" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserInfo_UserInfo" Member="UserInfo2" ThisKey="UserId" OtherKey="UserId" Type="UserInfo" Cardinality="One" />
      <Association Name="UserInfo_UserInfo" Member="UserInfo1" ThisKey="UserId" OtherKey="UserId" Type="UserInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PasswordInfo" Member="PasswordInfos">
    <Type Name="PasswordInfo">
      <Column Name="PasswordId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LabelType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PasswordInfo_PasswordInfo" Member="PasswordInfo2" ThisKey="PasswordId" OtherKey="PasswordId" Type="PasswordInfo" Cardinality="One" />
      <Association Name="PasswordInfo_PasswordInfo" Member="PasswordInfo1" ThisKey="PasswordId" OtherKey="PasswordId" Type="PasswordInfo" IsForeignKey="true" />
    </Type>
  </Table>
</Database>